const CREATE = 'CREATE'
const READ = 'FETCH_ALL'
const UPDATE = 'UPDATE'
const DELETE = 'DELETE'
const LIKE = 'LIKE'
const AUTH = 'AUTH'
const LOGOUT = 'LOGOUT'
export {CREATE, READ, UPDATE, DELETE, LIKE, AUTH, LOGOUT}